### ISSUE TITLE
Overrides are turned into Members incorrectly on format

### ISSUE THREAD

**Issue by dtwiers** [JetBrains/fsharp-support#111]
Given
```
type Foo =
  | Blah
  override this.ToString() = "Bar"
```
And then autoformatting in Rider gives
```
type Foo -
  | Blah
  member this.ToString() = "Bar"
```

It's not an error, only a warning, but it's incorrect.
I'm also quite possibly missing some kind of setting somewhere, but I couldn't find one, so here I am.

**Comment by auduchinok** [comment]
The code reformat is being done by [Fantomas](https://github.com/fsprojects/fantomas) library and the issue is already fixed there. We've updated bundled Fantomas version in upcoming 2020.1 release. There are [preview builds](https://www.jetbrains.com/rider/nextversion/) available if you want to make sure it's been fixed for you.

**Comment by auduchinok** [comment]
I've just checked it on the code example above and it behaves as expected. Please let me know if it reproduces for you on 2020.1 on some other example.
