### ISSUE TITLE
"Code Lens" support for function types

### ISSUE THREAD

**Issue by tylerhartwig** [JetBrains/fsharp-support#20]
After switching to Rider every day now for F#, this is the only thing I miss from VsCode + Ionide.

I think it's an awesome feature for F#, how hard would it be to get something similar in Rider? Does the IDEA platform support this kind of annotation?

**Comment by realvictorprm** [comment]
As I implemented code lens for VIsual Studio I also thought about implementing it for Rider and so talked with someone about this but was told that there isn't such an API available yet for an suitable implementation.

**Comment by vasily-kirichenko** [comment]
https://youtrack.jetbrains.com/issue/RIDER-2278

![image](https://user-images.githubusercontent.com/873919/43949771-2d9c9e74-9c97-11e8-80cd-5bf4bc3d9f88.png)

**Comment by tylerhartwig** [comment]
Are there updated plans for this now that CodeVision has been implemented in Rider? :)

**Comment by vasily-kirichenko** [comment]
Any updates?

**Comment by auduchinok** [comment]
@tylerhartwig @vasily-kirichenko It's planned for 2019.2.
To get updates you can vote for the [issue](https://youtrack.jetbrains.com/issue/RIDER-22661) about the feature.

**Comment by drhumlen** [comment]
I'm still holding my breath for this feature :D

@auduchinok: Is there any ETA?

**Comment by vasily-kirichenko** [comment]
@drhumlen 

![EB948D6C-4A4D-43B0-88B6-0443431AA757](https://user-images.githubusercontent.com/873919/60708398-aa7e1f80-9f16-11e9-8eed-4035b2b45e1d.png)

😝

**Comment by realvictorprm** [comment]
@vasily-kirichenko did you implement it?

**Comment by vasily-kirichenko** [comment]
No, it was our awesome @auduchinok

**Comment by realvictorprm** [comment]
It's a bummer, I would have loved to do it myself 😄 However I didn't know that the necessary stuff is already in IntelliJ.

**Comment by drhumlen** [comment]
@vasily-kirichenko : woa woa wi wa! nice! 😄 

Is there any way to try it out now? What do I have to do?

**Comment by auduchinok** [comment]
@vasily-kirichenko is being shy here. He's done a great job of prettifying presentation and covering some cases missing in my prototype. 🙂

@drhumlen You'll need to build the plugin locally to test it. The most up to date version is in Vasily's [PR](https://github.com/JetBrains/fsharp-support/pull/53). It's still missing some crucial parts (like properly registering the provider and adding tests) so me (or Vasily 🙂) will have to finish all the stuff before merging it in.

**Comment by drhumlen** [comment]
@auduchinok: I see. It's nice to see it's in progress. I would very much like to use it right away, even if it's not 100% (registering providers?) or lacking in tests.

Is there any way for you toorelease it as an EAP/Beta even if it isn't perfect? And then finish up in upcoming PRs? Perhaps it could be a beta-toggle in the settings so people won't complain when it's not a 100%?

**Comment by vasily-kirichenko** [comment]
@drhumlen It's quite easy to build it yourself. See the dev guide. It's just a couple of gradle commands and a single .net solution build.

**Comment by drhumlen** [comment]
@vasily-kirichenko: I see. I tried cloning your repo and opening it in Rider, but there's just too many IDE errors. Something about my local mono installation being too new (I have 5.x, but the project seems to require 4.x-series?). Not sure how to juggle multiple different versions of mono on my machine simultaneously (I'm not a .NET expert, as you can tell).

Is there any chance you could compile/zip it for me (and other future thread-visitors) so that I can install it in my current Rider? 😄

**Comment by auduchinok** [comment]
The inferred types provider for Code Vision is now merged in and most likely will be available for testing in the next EAP build.
Thanks to @vasily-kirichenko for his help with this feature.

**Comment by drhumlen** [comment]
This feature turned out really great btw 😄  It's very helpful to watch the type inference as I write out my function; even more so for function that are polymorphic. Thanks for making this @auduchinok  @vasily-kirichenko !

Question though: As of now, it only shows inferred type for top-level function/bindings & top-level inside module/class. It would be great to have the option to also see the type of _local_ let-bindings – perhaps as an option? My functions and variables are mostly inside another function/binding, so an option to show inferred type for _all_ bindings would be a game changer

**Comment by vasily-kirichenko** [comment]
@drhumlen After using the feature for a while, and because of https://youtrack.jetbrains.com/issue/RIDER-30413, I've switched it off :( It adds too much noise and effectively "reformat" code so that there are always empty lines. 

So, I'm against showing even more lenses.

**Comment by drhumlen** [comment]
@vasily-kirichenko: Oh, I show the lens information inline (ie. on the same line as my code), so I don't have that problem fortunately. I also use a dim/gray color for the lens information so it's never distracting. I highly recommend trying that. Having type information ready without the need to hover (which often doesn't work for me fsor) is gold.

...But it's definitely a good idea to make it optional so people who only prefer to have it "top-level" can stick with that.

**Comment by tylerhartwig** [comment]
I too would like additional, local lens support for type inference. I agree it would make sense to have them off by default, it would be really nice to have them separately configurable as well, so that some lenses may be inline (for local functions, ect), and top level ones could be placed elsewhere if desired. 

Personally, any scrolling effects do not bother me, and I love how configurable the IntelliJ platform is for each user.

**Comment by drhumlen** [comment]
@auduchinok: What do you think?

**Comment by auduchinok** [comment]
> @auduchinok: What do you think?
I would personally prefer using inline type hints than the lenses for local symbols. In any case it'd need some more work, though. :)

Adding lenses and turning them off by default may make some sense but I think almost nobody will ever turn them on as not many people seem to tinker with such settings at all. I don't mind having this feature optionally but, given the amount of people I expect to ever enable it, I can't say it'd get a high priority.

**Comment by drhumlen** [comment]
On by default then, with the option to turn it off? Also, people who dont tinker aren’t real developers if you ask me ;) should we really cater them first.?

Using lenses will make it even less intrusive than the inline rendering atm, so that sounds good.

@auduchinok  But would it be possible to extend the current behaviour to local let-s now as a low-hanging fruit? Is it any harder than restricting it to top-level let-s?

**Comment by tylerhartwig** [comment]
I also think it being on by default wouldn't be a big deal, if the lens default location was inline rather than overhead.
