### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [JetBrains/fsharp-support#6]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like fsharp-support, deleted the software history during the transition to open-source.

https://github.com/JetBrains/fsharp-support/commit/051cd658d3a6c7f475022d1022372d27a71d3cf5

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask fsharp-support developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by auduchinok** [comment]
Hi @gustavopinto,

I'm apologise for the late reply. The most of the history is actually remained in the repo. The commit you're referring to was at the point when initial F# support has been moved from Rider/ReSharper codebase to a separate plugin, not at the time we've open-sourced it.
It's been several months since that commit and before the repo went public, so the most of the history is available.

There was no intention to hide the history and as it was in the very initial state most of the files from the commit has changed a lot since and it didn't bring any trouble not having the history from the very beginning.

**Comment by gustavopinto** [comment]
Hi @auduchinok,

thanks for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
